targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - yp.schema.graphql
    builders:
      artemis:
        options:
          # fragments_glob: graphql/**.fragment.graphql
          scalar_mapping:
            - graphql_type: DateTime
              dart_type: DateTime
            - graphql_type: PartialDateTime
              dart_type: DateTime
          schema_mapping:
            - schema: yp.schema.graphql
              queries_glob: graphql/user.query.graphql
              output: lib/graphql/user_query.dart