name: yonomi_platform_sdk
description: Flutter SDK for Yonomi Platform
version: 5.0.2
homepage: https://www.yonomi.co

environment:
  sdk: ">=2.16.0 <3.0.0"

false_secrets:
  - test/e2e/repository/graph_link_test.dart
  - node_modules/

dependencies:
  equatable: ^2.0.3
  meta: ^1.7.0
  gql_exec: ^0.3.0
  gql: ^0.13.0
  gql_link: ^0.4.0
  http: ^0.13.4
  gql_http_link: ^0.4.0
  yaml: ^3.1.0
  dotenv: ^4.0.1
  gql_code_builder: ^0.2.0
  built_value: ^8.2.0
  built_collection: ^5.1.1
  dart_jsonwebtoken: ^2.4.2

dev_dependencies:
  mockito: ^5.0.15
  test: ^1.18.1
  nock: ^1.2.0
  build_runner: ^2.1.10
  gql_build: ^0.2.0
