name: yonomi_platform_sdk
description: Flutter SDK for Yonomi Platform
version: 2.7.0
homepage: https://www.yonomi.co

environment:
  sdk: ">=2.14.0 <3.0.0"
  
dependencies:
  equatable: ^2.0.3
  meta: ^1.3.0
  gql_exec: ^0.3.0
  gql: ^0.13.0
  gql_link: ^0.4.0
  http: ^0.13.4
  gql_http_link: ^0.4.0
  yaml: ^3.1.0
  dotenv: ^3.0.0
  corsac_jwt: ^1.0.0-nullsafety.1
  gql_code_builder: ^0.2.0
  built_value: ^8.1.3
  built_collection: ^5.1.1

dev_dependencies:
  mockito: ^5.0.15
  test: ^1.15.7
  nock: ^1.1.2
  build_runner: ^2.1.4
  gql_build: ^0.2.0
