name: yonomi_platform_sdk
description: >-
  The Yonomi Platform SDK aims to lower the curve to getting
  an application connected to the Yonomi Platform and
  working with objects in the IoT domain.
  By simplifying the developer experience of the Platform API,
  the SDK will speed up development time for prototypes and
  full production solutions. It will make interacting
  with the platform a more enjoyable developer experience,
  and allow the developer to focus on problems specific to
  their application domain and not necessarily specific to
  the minutia of Yonomi’s implementation of GraphQL.
version: 5.1.0
homepage: https://www.yonomi.com
repository: https://github.com/Yonomi/yonomi-sdk-dart
issue_tracker: https://github.com/Yonomi/yonomi-sdk-dart/issues

environment:
  sdk: ">=2.16.0 <3.0.0"

false_secrets:
  - test/e2e/repository/graph_link_test.dart
  - node_modules/

dependencies:
  equatable: ^2.0.3
  meta: ^1.7.0
  gql_exec: ^0.3.0
  gql: ^0.13.0
  gql_link: ^0.4.0
  http: ^0.13.4
  gql_http_link: ^0.4.0
  yaml: ^3.1.0
  dotenv: ^4.0.1
  gql_code_builder: ^0.2.0
  built_value: ^8.2.0
  built_collection: ^5.1.1
  dart_jsonwebtoken: ^2.4.2

dev_dependencies:
  mockito: ^5.0.15
  test: ^1.18.1
  nock: ^1.2.0
  build_runner: ^2.1.10
  gql_build: ^0.2.0
