name: yonomi_platform_sdk
description: A new Flutter package project.
version: 0.0.1
author: Yonomi
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  
dependencies:
  http: ^0.12.2
  safe_config: ^2.0.2

dev_dependencies:
  test: ^1.15.7
  nock: ^1.1.2