name: yonomi_platform_sdk
description: Flutter SDK for Yonomi Platform
version: 3.0.0
homepage: https://www.yonomi.co

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  meta: ^1.7.0
  gql_exec: ^0.4.0
  gql: ^0.13.0
  gql_link: ^0.4.2
  http: ^0.13.4
  gql_http_link: ^0.4.2
  yaml: ^3.1.0
  dotenv: ^4.0.1
  corsac_jwt: ^1.0.0-nullsafety.1
  gql_code_builder: ^0.5.0
  built_value: ^8.1.4
  built_collection: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  nock: ^1.2.0
  build_runner: ^2.1.8
  gql_build: ^0.4.0
