name: yonomi_platform_sdk
description: A new Flutter package project.
version: 0.0.1
author: Yonomi
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  
dependencies:
  http: ^0.12.2
  safe_config: ^2.0.2
  dotenv: ^2.0.0
  json_annotation: ^3.1.0
  equatable: ^1.2.5
  gql: '>=0.12.3 <1.0.0'
  

dev_dependencies:
  test: ^1.15.7
  nock: ^1.1.2
  artemis: '>=6.0.0 <7.0.0'
  build_runner: ^1.10.4
  json_serializable: ^3.5.0