name: yonomi_platform_sdk
description: Flutter SDK for Yonomi Platform
version: 0.1.0
homepage: https://www.yonomi.co

environment:
  sdk: ">=2.7.0 <3.0.0"
  
dependencies:
  http: ^0.12.2
  yaml: ^2.2.1
  dotenv: ^2.0.0
  artemis: '>=6.0.0 <7.0.0'
  json_annotation: ^3.1.0
  equatable: ^1.2.5
  gql: '>=0.12.3 <1.0.0'
  corsac_jwt: ^0.4.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.15.7
  nock: ^1.1.2
  build_runner: ^1.10.4
  json_serializable: ^3.5.0
  mockito: ^4.1.4
