name: yonomi_platform_sdk
description: Flutter SDK for Yonomi Platform
version: 1.0.6
homepage: https://www.yonomi.co

environment:
  sdk: ">=2.14.0 <3.0.0"
  
dependencies:
  equatable: ^1.2.5
  meta: ^1.3.0
  gql_exec: ^0.3.0
  gql: ^0.13.0
  gql_link: ^0.4.0
  http: ^0.13.4
  gql_http_link: ^0.4.0
  yaml: ^3.1.0
  dotenv: ^3.0.0
  corsac_jwt: ^1.0.0-nullsafety.1

dev_dependencies:
  test: ^1.15.7
  nock: ^1.1.2
  build_runner: ^2.1.4
  gql_build: ^0.2.0

