version: 2.1

#####################
# Common Definitions
#####################

# Orb declarations
orbs:
  codecov: codecov/codecov@1.0.2

executors:
  default-executor:
    docker:
      - image: cirrusci/flutter:stable

main_only: &main_only
  filters:
    branches:
      only: main

commands:
  unit-tests:
    description: "Run local unit tests"
    steps:
      - run:
          name: command to run unit tests
          command: pub run test test/unit --reporter json | tojunit --output test-results/dart-tests/dart_sdk_unit_tests-report.xml
  e2e-tests:
    description: "Run end-to-end tests"
    steps:
      - run:
          name: command to run e2e tests
          command: pub run test test/e2e --reporter json | tojunit --output test-results/dart-tests/dart_sdk_e2e_tests-report.xml
  run-tests:
    description: "Run all tests"
    steps:
      - run:
          name: command to run all tests
          command: PRIVATE_KEY=$(echo "$PRIVATE_KEY_ENCODED" | base64 --decode) flutter test --coverage && lcov --remove coverage/lcov.info 'lib/graphql/*' > coverage/lcov1.info
      - codecov/upload:
          file: coverage/lcov1.info
  run-semantic-versioning:
    description: "Tag and create changelog"
    steps:
      - run:
          name: Git Setup
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git config --global user.email "developer@yonomi.co"
            git config --global user.name "CircleCI"
      - run: sudo apt-get update
      - run: sudo apt-get -y install npm
      - run: |
          npm init -y
          npm i -D @semantic-release/changelog
          npm i -D @semantic-release/git
          npm i -D semantic-release-dart
          npx semantic-release --branches main
  run-publish:
    description: "Publishes to pub.dev"
    steps:
      - run:
          name: Publishing to pub.dev
          command: dart pub publish --dry-run

  dependencies:
    description: "Download dependencies and setup global packages"
    parameters:
      shell:
        type: string
        default: "/bin/bash --login -eo pipefail"
      pub-cache:
        type: string
        default: "~/.pub-cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.4-dependencies-{{ arch }}-{{ checksum "pubspec.lock" }}
            - v1.4-dependencies-{{ arch }}-
      - run:
          name: Download deps
          shell: << parameters.shell >>
          command: pub get
      - run:
          name: Get junitreporter
          shell: << parameters.shell >>
          command: pub global activate junitreport
      - save_cache:
          key: v1.4-dependencies-{{ arch }}-{{ checksum "pubspec.lock" }}
          paths:
            - .dart_tool
            - << parameters.pub-cache >>

  

##################
# Job Definitions
##################
jobs:
  test:
    executor: default-executor
    steps:
      - dependencies:
          shell: "/bin/bash -eo pipefail"
      - run:
          name: Make folder for test results
          command: mkdir -p test-results/dart-tests
      - run-tests
      - store_test_results:
          path: test-results
  semantic-versioning:
    executor: default-executor
    steps:
      - dependencies:
          shell: "/bin/bash -eo pipefail"
      - run-semantic-versioning
  publish:
    executor: default-executor
    steps:
      - dependencies:
          shell: "/bin/bash -eo pipefail"
      - run-publish

######################
# Workflow Definition
######################
workflows:
  version: 2.1
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
  test-changelog-tag:
    jobs:
      - test:
          <<: *main_only  
      - semantic-versioning:
          context:
            - org-global
          requires:
              - test
          <<: *main_only
  test-publish:
    when:
      equal: [ private, "${REPO_TYPE}" ]
    jobs:
      - test:
          filters:
              branches:
                only:
                  - test_publish
      - hold:
          type: approval
          requires:
            - test
      - publish:
          requires:
            - hold
          filters:
            branches:
              only:
                - test_publish

